### ISSUE TITLE
How do you apply a dark material UI theme?

### ISSUE THREAD

**Issue by patrickklze** [eclipsesource/jsonforms-angular-seed#14]
Hi Team,

Can i check if i am planning to use a dark theme for my Angular Project, how do i apply it here?

**Comment by AlexandraBuzila** [comment]
Hi @patrickklze! Our JSON Forms Angular Material renderers can be styled with Material's theme support. Some (but not many) of our renderers are not fully compatible with the theming. We would gladly accept contributions fixing that. Alternatively, we also offer professional support:  https://jsonforms.io/support
