### ISSUE TITLE
Angular 10 integration problem 

### ISSUE THREAD

**Issue by skandula106** [eclipsesource/jsonforms-angular-seed#16]
Hai I am trying to intergrade **jsonforms-angular-seed** to my angular 10 project i am getting errors i followed all the things installed all packages which r described in this project taken angular 10 updated branch can you please any one help me with this i am sharing my errors screen shot below 
![Capture issue](https://user-images.githubusercontent.com/58414973/101056620-2ddeed00-35b1-11eb-963c-3a5e27fb9a97.PNG)

**Comment by sdirix** [comment]
Hi @skandula106, we can help you much better if you could provide your actual code. Please compare our `tsconfig`s and `package.json` with yours and see whether you are missing some required settings, e.g. [`browser: {http: false, https: false}`](https://github.com/eclipsesource/jsonforms-angular-seed/blob/943c5fc3ae0d3b6409cc6aa3d863a13c2a39a9c4/package.json#L62-L65)

**Comment by skandula106** [comment]
I am compared and installed required packages also Can u please create new angular 10 project and intigret your code and share to me or I will share my code look and clear the errors if possible it is very helpful from

**Comment by skandula106** [comment]
Here is my project source code browser settings not present this branch 
[Uploading json-angular form.zip…]()

**Comment by eneufeld** [comment]
Hi @skandula106 @sandeepreddy1248 , 
so I was looking into the zip you uploaded.
The easiest solution I see is to fix you `angular.json` file by letting it use the `tsconfig.app.json` and `tsconfig.spec.json` from src:
`"tsConfig": "src/tsconfig.app.json",`
furthermore you must update the `polyfill.ts` as is done in this repo:
```ts
(window as any).global = window;
// @ts-ignore
window.Buffer = window.Buffer || [];
(window as any).process = {env: { DEBUG: undefined }, version: [], cwd:() => ''};
```
I hope this helps
