### ISSUE TITLE
Unable to integrate in angular 10 application

### ISSUE THREAD

**Issue by sandeepreddy1248** [eclipsesource/jsonforms-angular-seed#18]
Hi Sdirix, Whatever you provide link(https://github.com/eclipsesource/jsonforms-angular-seed) it is working fine when i do nppm install in this jsonforms-angular-seed project but i have installed new angular10 project and trying to integrated then i am getting below error.
![Capture](https://user-images.githubusercontent.com/43595350/101073629-bf2c7000-356d-11eb-9300-f1082eea2dce.PNG)

here is the project code 
https://github.com/eclipsesource/jsonforms/files/5638296/angular10.zip

**Comment by sdirix** [comment]
Please don't spam this issue tracker. Closed as duplicate of #16.
