### ISSUE TITLE
Is it possible to build custom ui schemas

### ISSUE THREAD

**Issue by jloracudris** [eclipsesource/jsonforms-angular-seed#22]
Hi Guys i have a question more than an issue

I have this requirement, i have a schema, i want to be able to automatically create an ui schema to render it but not as the default that is created with `Generate.uiSchema`, i want to be able to generate it but with lets say in two or three columns not in one single column, for example, this form right here in the docs:

https://jsonforms.io/examples/layouts#nested-layouts

how can i generate a ui schema to render something like this

![image](https://user-images.githubusercontent.com/17204647/111403462-07921880-869b-11eb-869e-0005df748d84.png)

Thanks in advance, hope the question is clear enough

**Comment by sdirix** [comment]
Hi @jloracudris, I would recommend to write your own ui schema generator. You can just copy [our ui schema generator code](https://github.com/eclipsesource/jsonforms/blob/e16e5086de06d9b7cbade89d07b0a5e6879eb57e/packages/core/src/generators/uischema.ts), which is really not that much, and modify it to your liking. You then generate the ui schema before handing it over to JSON Forms.

**Comment by jloracudris** [comment]
Hey @sdirix Thanks for the quick answer ill try make my own then
