### ISSUE TITLE
Error: Can't resolve 'http' nor 'https'

### ISSUE THREAD

**Issue by paulovich10** [eclipsesource/jsonforms-angular-seed#32]
Hi, I'm getting this error, and I would appreciate any help. 

```
Error: ./node_modules/json-schema-ref-parser/lib/resolvers/http.js
Module not found: Error: Can't resolve 'https' in '/Users/barbaraiot/Desktop/kubernetes/barbara_panel_frontend/node_modules/json-schema-ref-parser/lib/resolvers'Error: ./node_modules/json-schema-ref-parser/lib/resolvers/http.js
Module not found: Error: Can't resolve 'http' in '/Users/barbaraiot/Desktop/kubernetes/barbara_panel_frontend/node_modules/json-schema-ref-parser/lib/resolvers'

Error: ./node_modules/json-schema-ref-parser/lib/resolvers/http.js
Module not found: Error: Can't resolve 'https' in '/Users/barbaraiot/Desktop/kubernetes/barbara_panel_frontend/node_modules/json-schema-ref-parser/lib/resolvers'
```

Steps to reproduce:

1 npm i --save @jsonforms/core @jsonforms/angular @jsonforms/angular-material

2 added  "allowSyntheticDefaultImports": true, in compilerOptions

3 Added  "browser": { "http": false, "https": false }, in package.json

Until here, everything is correct, it compiles.

4. Import modules in module.ts

```
import { JsonFormsModule } from "@jsonforms/angular";
import { JsonFormsAngularMaterialModule } from "@jsonforms/angular-material";

```
5 add the modules in imports array

6. error compiling
I'm using angular 11 with typescript": "4.0.5" running on a IOS 11.2.3 
 I also get the following warning in the npm i step 

```Warning: Entry point '@jsonforms/angular-material' contains deep imports into '/Users/barbaraiot/Desktop/kubernetes/barbara_panel_frontend/node_modules/@jsonforms/angular/lib/abstract-control'. This is probably not a problem, but may cause the compilation of entry points to be out of order.```

**Comment by sdirix** [comment]
Hi @paulovich10, you need to upgrade to the JSON Forms 3.0 Alpha stream, for more information see [here](https://github.com/eclipsesource/jsonforms/issues/1761).

**Comment by paulovich10** [comment]
Thanks, I understand 3.0 Alpha in NG 11 compatible?

**Comment by sdirix** [comment]
Closing this issue as it's very old and outdated. Feel free to reopen with more information if you still encounter this problem.
