### ISSUE TITLE
Duplicate seeds

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/jsonforms-angular-seed#5]
We currently have two seeds based on Angular, this one and the other one at https://github.com/eclipsesource/angular-jsonforms-webpack.

We should clarify which one to use in the future.

**Comment by eneufeld** [comment]
I can't get this out running, if I clean it from scratch.
Does it work for you?

**Comment by edgarmueller** [comment]
With the changes from the PR merged two hours ago, it does. What the issue? By 'clean from scratch' you mean cloning this repo, installing the dependencies and run `ng serve`?

**Comment by eneufeld** [comment]
Exactly.
I will retry and let you know if it works now for me.

**Comment by eneufeld** [comment]
I get this errors:
`ERROR in /home/eugen/Git/jsonforms-angular-seed/node_modules/jsonforms/dist/ts-build/models/uischema.d.ts (23,12): In ambient enum declarations member initializer must be constant expression.
/home/eugen/Git/jsonforms-angular-seed/node_modules/jsonforms/dist/ts-build/models/uischema.d.ts (27,12): In ambient enum declarations member initializer must be constant expression.
/home/eugen/Git/jsonforms-angular-seed/node_modules/jsonforms/dist/ts-build/models/uischema.d.ts (31,14): In ambient enum declarations member initializer must be constant expression.
/home/eugen/Git/jsonforms-angular-seed/node_modules/jsonforms/dist/ts-build/models/uischema.d.ts (35,15): In ambient enum declarations member initializer must be constant expression.

ERROR in AppModule is not an NgModule

ERROR in multi ./src/styles.css
Module not found: Error: Can't resolve 'css-loader?{"sourceMap":false,"importLoaders":1}' in '/home/eugen/Git/jsonforms-angular-seed'
 @ multi ./src/styles.css

ERROR in multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
Module not found: Error: Can't resolve '@ngtools/webpack' in '/home/eugen/Git/jsonforms-angular-seed'
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in multi ./src/polyfills.ts
Module not found: Error: Can't resolve '@ngtools/webpack' in '/home/eugen/Git/jsonforms-angular-seed'
 @ multi ./src/polyfills.ts

ERROR in   Error: Child compilation failed:
  Entry module not found: Error: Can't resolve 'raw-loader' in '/home/eugen/Git/  jsonforms-angular-seed':
  Error: Can't resolve 'raw-loader' in '/home/eugen/Git/jsonforms-angular-seed'
  
  - compiler.js:76 
    [jsonforms-angular-seed]/[cli]/[html-webpack-plugin]/lib/compiler.js:76:16
  
  - Compiler.js:280 Compiler.<anonymous>
    [jsonforms-angular-seed]/[cli]/[webpack]/lib/Compiler.js:280:10
  
  - Compiler.js:480 
    [jsonforms-angular-seed]/[cli]/[webpack]/lib/Compiler.js:480:13
  
  - Tapable.js:202 next
    [jsonforms-angular-seed]/[cli]/[tapable]/lib/Tapable.js:202:11
  
  - CachePlugin.js:62 Compiler.<anonymous>
    [jsonforms-angular-seed]/[cli]/[webpack]/lib/CachePlugin.js:62:5
  
  - Tapable.js:206 Compiler.applyPluginsAsyncSeries
    [jsonforms-angular-seed]/[cli]/[tapable]/lib/Tapable.js:206:13
  
  - Compiler.js:477 
    [jsonforms-angular-seed]/[cli]/[webpack]/lib/Compiler.js:477:10
  
  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [jsonforms-angular-seed]/[cli]/[tapable]/lib/Tapable.js:195:46
  
  - Compilation.js:640 self.applyPluginsAsync.err
    [jsonforms-angular-seed]/[cli]/[webpack]/lib/Compilation.js:640:19
  
  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [jsonforms-angular-seed]/[cli]/[tapable]/lib/Tapable.js:195:46
  
  - Compilation.js:631 self.applyPluginsAsync.err
    [jsonforms-angular-seed]/[cli]/[webpack]/lib/Compilation.js:631:11
  
  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [jsonforms-angular-seed]/[cli]/[tapable]/lib/Tapable.js:195:46
  
  - Compilation.js:626 self.applyPluginsAsync.err
    [jsonforms-angular-seed]/[cli]/[webpack]/lib/Compilation.js:626:10
  
  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [jsonforms-angular-seed]/[cli]/[tapable]/lib/Tapable.js:195:46
  
  - Compilation.js:622 sealPart2
    [jsonforms-angular-seed]/[cli]/[webpack]/lib/Compilation.js:622:9
  
  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [jsonforms-angular-seed]/[cli]/[tapable]/lib/Tapable.js:195:46
  


ERROR in multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
Module not found: Error: Can't resolve 'webpack-dev-server/client?http://localhost:4200' in '/home/eugen/Git/jsonforms-angular-seed'
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
`

node version: 8.9.0
npm version: 5.5.1
global typescript is 2.5.3
typescript in node_modules is 2.4.2

**Comment by edgarmueller** [comment]
I think this is caused by an incompatible Angular CLI (global vs local.) Can you check whether that is the case for you? Perhaps we should update the Angular CLI version anyways since it still points to 1.0.0
