### ISSUE TITLE
Loading schemas from HTTP breaks the example

### ISSUE THREAD

**Issue by marcobuschini** [eclipsesource/jsonforms-angular-seed#60]
Have a look at this fork of mine to see a cryptic "No applicable renderer found!" error message: [https://github.com/marcobuschini/jsonforms-angular-seed](https://github.com/marcobuschini/jsonforms-angular-seed)

I made small changes to your seed project so that data, schema, and uiSchema can be loaded from http requests via observables and async pipes. I am supposed to be able to use observables there, aren't I?

**Comment by sdirix** [comment]
Hi @marcobuschini,

No at the moment that is not possible. We expect regular objects as parameters. So you will need to wait until your data is resolved and only then hand it over to JSON Forms.

**Comment by marcobuschini** [comment]
Hi @sdirix,
does this mean that schema and uiSchema must be statically defined in the code? Or can I subscribe/await for schemas to be available and then give the schemas to jsonForms?

**Comment by marcobuschini** [comment]
To do this you must resolve the observables into scalar variables, and then run change detection (component change detection strategy is OnPush).

Example on how to do this:

```
@Component({
  selector: ...,
  templateUrl: ...,
  styleUrls: [...],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MyEditComponent implements OnInit {
  public constructor(
    public backend: BackendService,
    public changeDetector: ChangeDetectorRef,
  ) {}

  public async ngOnInit(): Promise<void> {
    this.jsonSchema = await lastValueFrom(this.backend.loadSchema());
    this.uiSchema = await lastValueFrom(this.backend.loadUiSchema());
    this.changeDetector.detectChanges();
  }
}
```

**Comment by sdirix** [comment]
Closing this issue as the question was answered.
