### ISSUE TITLE
Is there way to pass flex style in angular material ?

### ISSUE THREAD

**Issue by contactzen** [eclipsesource/jsonforms-angular-seed#72]
Hi Guys , 

It is great tool, thank you for building such great tool.

I have this requirement, i have a schema where rather than 50/50 split in HorizontalLayout i want to do more of 20/80 split. How can I achieve this ?

Thank you in advance

**Comment by sdirix** [comment]
HI @contactzen,

This can be achieved using a custom layout renderer. Each renderer has full control over their rendered output, so you can implement any split you like to see.

Note that our [Discourse](https://jsonforms.discourse.group] is a better place to post questions ;)
