### ISSUE TITLE
Wrong date format parsed on german locale/angular

### ISSUE THREAD

**Issue by wuedev** [eclipsesource/jsonforms-angular-seed#75]
I have set up a simple form based on the angular seed. Locale is set to "de-DE". The datepicker displays german labels for months etc. and the selected date is displayed in the correct german format (1.10.2010). 

However, typing a date directly into the date field doesen't work as expected - typing in '1.10.2010' the date is changed to '9.1.2010. It appears that the months is decreased by one and then month and day are exchanged, so it seems that the original american date format (MM.DD.YYYY) is used for parsing. I have set an option "dateFormat" on the date control in uischema.json, which has no effect.

**Comment by christian-smietana** [comment]
Wrong repo...

**Comment by lucas-koehler** [comment]
Superseded by https://github.com/eclipsesource/jsonforms/issues/2244
