### ISSUE TITLE
Individual form control data does not update jsonform

### ISSUE THREAD

**Issue by muleakshay29** [eclipsesource/jsonforms-angular-seed#79]
In JSONform, the bound data does not update the contents of the Name field as shown below. I have created a custom renderer for the text field, and if I update the value, it does not reflect in the main data bound to JSONform.

<img width="934" alt="image" src="https://github.com/eclipsesource/jsonforms-angular-seed/assets/13780594/d4e72aa7-55d3-4955-8973-538cce7b4dc6">

**Comment by sdirix** [comment]
This is not really a topic for the `jsonforms-angular-seed`. If there is an issue with JSON Forms you can open an issue against the [main repository](/eclipsesource/jsonforms). However I would recommend posting in our [discussion board](https://jsonforms.io). 

In any case please add the code of your custom renderer. Without we will not be able to help you diagnose what is going wrong.

**Comment by B-Simms** [comment]
@muleakshay29 did you ever get a resolution for this? I'm getting the same issue, and vscode tells me there's a problem with JsonFormsModule not being recognized as a known element even though it's declared in app.module.ts.
